dags:
  gitSync:
    enabled: true
    repo: "https://github.com/JonZudell/wx-de-fe-be.git"
    branch: development
    subPath: "services/airflow/dags/"

scheduler:
  logCleanup:
    ## WARNING: scheduler log-cleanup must be disabled if `logs.persistence.enabled` is `true`
    enabled: false
    
workers:
  logCleanup:
    ## WARNING: workers log-cleanup must be disabled if `logs.persistence.enabled` is `true`
    enabled: false
logs:
  ## NOTE: this is the default value
  path: /opt/airflow/logs
  
  persistence:
    enabled: true
    ## NOTE: set `storageClass` to "" for the cluster-default
    storageClass: "default"
    ## NOTE: some types of StorageClass will ignore this request (for example, EFS)
    size: 5Gi
    ## WARNING: as multiple pods will write logs, this MUST be ReadWriteMany
    accessMode: ReadWriteMany
config:
  webserver:
    expose_config: 'True'
env:
-  name: AIRFLOW__CORE__LOAD_EXAMPLES
   value: "False"