dags:
  gitSync:
    enabled: true
    repo: github.com/JonZudell/wx-de-fe-be.git
    branch: development
    subPath: "services/airflow/dags/"
config:
  webserver:
    expose_config: 'True'
env:
-  name: AIRFLOW__CORE__LOAD_EXAMPLES
   value: "False"